/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.75).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorResponse;
import io.swagger.model.UsuarioValoraElem;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-11-19T10:28:12.285996221Z[GMT]")
@Validated
public interface UsuarioValoraElemApi {

    @Operation(summary = "Obtener todas las valoraciones de elementos por usuarios", description = "Devuelve todas las valoraciones realizadas por los usuarios a los elementos.", tags={ "Valoraciones" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Lista de valoraciones obtenida correctamente.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = UsuarioValoraElem.class)))),
        
        @ApiResponse(responseCode = "500", description = "Error interno del servidor.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/usuarioValoraElem",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<UsuarioValoraElem>> usuarioValoraElemGet();

    @Operation(summary = "Obtener todas las valoraciones de un elemento por usuarios", description = "Devuelve todas las valoraciones realizadas por los usuarios a un elemento.", tags={ "Valoraciones" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Lista de valoraciones obtenida correctamente.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = UsuarioValoraElem.class)))),
        
        @ApiResponse(responseCode = "500", description = "Error interno del servidor.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/usuarioValoraElem/{idelemento}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<UsuarioValoraElem>> getComentariosElem(@Parameter(in = ParameterIn.PATH, description = "ID del elemento", required=true, schema=@Schema()) @PathVariable("idelemento") Integer idelemento);


    @Operation(summary = "Eliminar la valoración de un usuario para un elemento", description = "Borra la valoración realizada por un usuario a un elemento específico.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Valoraciones" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Valoración eliminada correctamente (sin cuerpo de respuesta)."),
        
        @ApiResponse(responseCode = "500", description = "Error interno del servidor.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/usuarioValoraElem/{idUsuario}/{idElemento}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> usuarioValoraElemIdUsuarioIdElementoDelete(@Parameter(in = ParameterIn.PATH, description = "ID del usuario", required=true, schema=@Schema()) @PathVariable("idUsuario") Integer idUsuario
, @Parameter(in = ParameterIn.PATH, description = "ID del elemento", required=true, schema=@Schema()) @PathVariable("idElemento") Integer idElemento
);


    @Operation(summary = "Verificar si un usuario ha valorado un elemento", description = "Devuelve la valoracion del usuario para el elemento especificado.", tags={ "Valoraciones" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Resultado de la verificación.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))),
        
        @ApiResponse(responseCode = "500", description = "Error interno del servidor.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/usuarioValoraElem/{idUsuario}/{idElemento}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Integer> usuarioValoraElemIdUsuarioIdElementoGet(@Parameter(in = ParameterIn.PATH, description = "ID del usuario", required=true, schema=@Schema()) @PathVariable("idUsuario") Integer idUsuario
, @Parameter(in = ParameterIn.PATH, description = "ID del elemento", required=true, schema=@Schema()) @PathVariable("idElemento") Integer idElemento
);


    @Operation(summary = "Crear una nueva valoración de un usuario para un elemento", description = "Registra una nueva valoración realizada por un usuario a un elemento específico.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Valoraciones" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Valoración creada correctamente.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = UsuarioValoraElem.class))),
        
        @ApiResponse(responseCode = "400", description = "Datos de entrada inválidos.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "Error interno del servidor.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/usuarioValoraElem",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<UsuarioValoraElem> usuarioValoraElemPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody UsuarioValoraElem body
);


    @Operation(summary = "Actualizar una valoración de un usuario para un elemento", description = "Modifica la valoración realizada por un usuario a un elemento específico.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Valoraciones" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Valoración actualizada correctamente.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = UsuarioValoraElem.class))),
        
        @ApiResponse(responseCode = "400", description = "Datos de entrada inválidos.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "Error interno del servidor.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/usuarioValoraElem",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<UsuarioValoraElem> usuarioValoraElemPut(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody UsuarioValoraElem body);

}

